### PR TITLE
Merge dev into master

### PR DESCRIPTION
**Pull request by naved001**
I think we need to change some link in the ReadMe. Besides that, do we need to change anything else?

### CODE REVIEW

**Comment by naved001** [comment]
cc: @pgrosu @apoorvemohan

**Comment by naved001** [comment]
Fixes #102

**Comment by naved001** [comment]
had a discussion with @chemistry-sourabh 

we would need to make several changes in the readme. but we can't do this in this PR otherwise that would break the readme in the `dev` branch.

changes are:
  * change link to image
  * link to build and coverage tags on top of readme.

**Comment by pgrosu** [comment]
+1

**Comment by apoorvemohan** [comment]
I would like to see the list of raised issues after running UATs. As UATs have not being reviewed, I would like to verify those issue once.

**Comment by naved001** [comment]
You might wanna look for @pgrosu's comments on previous 4-5 PRs that we merged.

**Comment by pgrosu** [comment]
It is probably most efficient for me to write the manual for the UAT framework, and provide it to the whole team.  This would include the different system configurations, as some of the issues we encountered on different systems were communicated orally, as we were working together to make implementations operational.  Probably the most significant issue this summer - while running and stress-testing with the UAT - was that we learned BMI was using the same Ceph cluster for both production and development (see https://github.com/CCI-MOC/ims/issues/122#issuecomment-308927324), which also made us aware a delay between image creation and bmi-importing is necessary because of how the Ceph architecture reaches consistency.  The scope of the UAT was to ensure that we catch most of the common use cases - through an end-to-end scenario - so that when folks use it in production - or to learn via the BMI User's Guide (chapter 2) - it will not affect our focus on the redesign with such a small team.

**Comment by apoorvemohan** [comment]
Had a discussion with Gene - if we have any issues, we will release a 0.6

**Pull request merged**
