### PR TITLE
Imports

### PR DESCRIPTION
**Pull request by chemistry-sourabh**
Issue #27

### CODE REVIEW

**Comment by sirushtim** [comment]
Nice work, but it seems like there is still some more imports to fix in the codebase.

ims/einstein/iscsi/iet.py:from ims.interfaces.iscsi import *
scripts/einstein_server:from ims.rpc.server.name_server import *
scripts/einstein_server:from ims.rpc.server.rpc_server import *
tests/database/test_project.py:from ims.database.database import *
tests/database/test_image.py:from ims.database import *
tests/einstein/test_operations.py:from ims.database import *
tests/picasso/test_rest.py:from ims.database import *

**Comment by ravisantoshgudimetla** [comment]
I think @chemistry-sourabh wants to ignore both tests and iet.py but scripts/einstein is something that has to be fixed.

**Comment by ravisantoshgudimetla** [comment]
@chemistry-sourabh: Squash the commits as well, it will be difficult to debug later, if we have too many commits(in case we want to do a git bisect and find which commit caused the issue).

**Comment by chemistry-sourabh** [comment]
Fixed all except tests (Ignore them for now as they will be fixed when doing tests)

**Comment by sirushtim** [comment]
I agree with the idea of squashing commits for PR's. One commit, one logical change per PR. It makes it a lot easier to review too.

Not sure why we don't want to do fix imports in tests with this change, but otherwise, looks good to me.

**Comment by chemistry-sourabh** [comment]
After a lot of rebases finally squashed everything and also got travis to work again. (Atleast mastered rebasing now)

**Comment by chemistry-sourabh** [comment]
@sirushtim tests need to rewritten as they won't work now. Can fix everything when doing that

**Comment by chemistry-sourabh** [comment]
@naved001 or @ravisantoshgudimetla can be the second reviewer

**Comment by ravisantoshgudimetla** [comment]
+1 and merging.

**Comment by sirushtim** [comment]
@chemistry-sourabh Ah I see. Cool. Thanks.

**Pull request merged**
