### PR TITLE
Pep8

### PR DESCRIPTION
**Pull request by chemistry-sourabh**
Issue #38 #26 
This PR enables the correct Travis PEP8 Tests

### CODE REVIEW

**Comment by naved001** [comment]
Okay I will run the tests manually (ill clone your code and then run it). But a better way to do it would be to setup Travis CI on your personal repo. To do that, just push the .travis.yml file to your repo, and setup an account on Travis CI. That way it will automatically run all the tests (pep8 for now) every time you make a commit.

**Comment by naved001** [comment]
There are a bunch of `E501 line too long (80 > 79 characters)`.

**Comment by chemistry-sourabh** [comment]
can you email me the log ?

**Comment by naved001** [comment]
Travis CI is now enabled. You should push the updated `.travis.yml` file (Ill email that) to this PR which enables pep8 tests.

**Comment by naved001** [comment]
+1
looks good to me.

**Comment by chemistry-sourabh** [comment]
@sirushtim or @ravisantoshgudimetla this is the next one that should be merged

**Comment by sirushtim** [comment]
Nice. +1

**Pull request merged**
