### PR TITLE
bugfix: HAAS TO HIL

### PR DESCRIPTION
**Pull request by xukan**
Bugfix [#51](https://github.com/CCI-MOC/ims/issues/51) change HAAS to HIL

### CODE REVIEW

**Comment by chemistry-sourabh** [comment]
@xukan the commit also looks ok

**Comment by chemistry-sourabh** [comment]
@naved001 this is merge ready. Do we want to merge this for the release ? I am going to have fun rebasing

**Comment by chemistry-sourabh** [comment]
What about merging this ? @naved001

**Comment by naved001** [comment]
@chemistry-sourabh the build failed on this one. :(

**Comment by chemistry-sourabh** [comment]
@naved001 the constant was changed to HIL_USERNAME from HAAS_USERNAME. The CI script needs to be updated in this PR.

**Comment by chemistry-sourabh** [comment]
@naved001 merge when you are jobless

**Comment by naved001** [comment]
@chemistry-sourabh I am worried about the nasty merge conflicts it would introduce with the other open PRs.

**Comment by chemistry-sourabh** [comment]
@naved001 we should merge it at some time. Whatever time we do it is going to introduce merge conflicts.

**Comment by naved001** [comment]
this has 2 sign offs, so I am merging this.

**Pull request merged**
