### PR TITLE
Generic Driver Loader

### PR DESCRIPTION
**Pull request by chemistry-sourabh**
Issue #30

### CODE REVIEW

**Comment by chemistry-sourabh** [comment]
@CCI-MOC/bmi-breakers this can also be reviewed. Note that the tgt should be loadable, but it is not a complete driver as there is no directory yet

**Comment by apoorvemohan** [comment]
@chemistry-sourabh As we discussed on Sunday, you have to break this PR into 2 separate PR's(1. "Generic ISCSI Plugable Framework" and 2. "TGT Driver").

Also, for March 15 release, we are aiming a robust version with TGT hardcoded.

**Comment by chemistry-sourabh** [comment]
I did that, so this won't be merged then ?

**Comment by apoorvemohan** [comment]
### I did that, so this won't be merged then?
  You did what? I didn't get this. 
### Also @ravisantoshgudimetla needs this right?
  Why Ravi needs this for the March 15 release?

**Comment by chemistry-sourabh** [comment]
Splitted the Generic Driver and ravi needs the Generic Driver for mocks right ?

**Comment by apoorvemohan** [comment]
@chemistry-sourabh Is there a separate PR for the generic driver? 
Mocks are not going in the March 15 release.

**Comment by naved001** [comment]
@chemistry-sourabh What's the status on this PR?

**Comment by naved001** [comment]
What's the status on this PR? @chemistry-sourabh

**Comment by chemistry-sourabh** [comment]
This also needs to be rebased

**Comment by chemistry-sourabh** [comment]
Rebased @CCI-MOC/bmi-breakers try it out

**Comment by naved001** [comment]
closing this for now until we decide how to redesign BMI.

**Pull request closed without merging**
