### PR TITLE
Update tests structure

### PR DESCRIPTION
**Pull request by chemistry-sourabh**
This is to update the tests structure as discussed.
@CCI-MOC/bmi-breakers ravi kind of liked this approach. I dont have a huge problem with it, but I preferred suffixing the test files as 'unit' or 'integration' instead of using the folders.

We can debate in  a separate PR whether a test is an unit or integration later, just focus on the directory structure.

The structure is supposed to mimic the structure of the ims folder.

### CODE REVIEW

**Comment by chemistry-sourabh** [comment]
Also review this first

**Comment by chemistry-sourabh** [comment]
@xukan just review the last commit that is Update tests strcuture. I had to rebase this on a commit which fixes tgt issues.
So post your suggestion in tgt-changes branch

**Comment by knikolla** [comment]
Please follow the ``tests/unit/<component>`` structure instead of ``tests/<component>/unit``. For examples ``tests/unit/einstein/operations/test_operations`` (even though the operations folder isn't really required because there's very few files).

**Comment by chemistry-sourabh** [comment]
I am fine with this. @ravisantoshgudimetla ?

**Comment by naved001** [comment]
@chemistry-sourabh I agree with @knikolla's idea. that way we can easily run all the unittests together. `python tests/unit/` and all the integration tests together 
`python(py.test or whatever) tests/integration/`

**Comment by chemistry-sourabh** [comment]
ok I will reorganize this and rebase other PRs

**Comment by chemistry-sourabh** [comment]
@ravisantoshgudimetla your attention is required here also

**Comment by chemistry-sourabh** [comment]
@knikolla please review changes

**Comment by ravisantoshgudimetla** [comment]
I have no strong opinion on this, fine with either of structures, my only concern is mapping the main folder structure with the ones that we decide here.

**Comment by chemistry-sourabh** [comment]
the folder structure is same as the main one in the unit or integration folders. The only thing left is to decide which test goes where

**Comment by ravisantoshgudimetla** [comment]
I didn't understand, so you want structure to be reviewed or file locations for individual tests?

**Comment by chemistry-sourabh** [comment]
Just the structure. The file locations are also fine, only it needs to be debated whether a test file is an integration or unit test. This can be done in another PR.

**Comment by chemistry-sourabh** [comment]
Do not merge yet!!

**Comment by chemistry-sourabh** [comment]
This has been rebased and ready to merge!!

**Pull request merged**
