### PR TITLE
Delete bmi_client.py

### PR DESCRIPTION
**Pull request by chemistry-sourabh**
Deleting bmi_client.py as it was pushed by mistake.
We will be writing a client lib later, but I feel that this incomplete file will cause confusions.
So can keep it if people find a strong reason to keep it.

### CODE REVIEW

**Comment by naved001** [comment]
I don't have a strong opinion on this. so +1

**Comment by sirushtim** [comment]
+1

**Comment by ravisantoshgudimetla** [comment]
I was under the impression, that this was used by other teams like Bigdata etc. Isn't it?

**Comment by chemistry-sourabh** [comment]
I wrote it for Rajul. Bigdata guys must be using the CLI.

**Pull request merged**
